const productos = [
    { "codigo": 1, "descripcion": "JUEGO DE ESCUADRA GRANDE", "cantidad": 11, "precio": 1.20, "costo": 0.60 },
    { "codigo": 2, "descripcion": "LAPICERO PAPER MATTE", "cantidad": 10, "precio": 0.30, "costo": 0.15 },
    { "codigo": 3, "descripcion": "ESCARCHA DE SOBRE", "cantidad": 43, "precio": 0.25, "costo": 0.13 },
    { "codigo": 4, "descripcion": "PINCEL ECONOMICO PLANO Y REDONDO", "cantidad": 6, "precio": 0.95, "costo": 0.55 },
    { "codigo": 5, "descripcion": "STICKER PARA CUADERNO NOMBRE", "cantidad": 2, "precio": 1.00, "costo": 0.50 },
    { "codigo": 6, "descripcion": "TIJERA FIGURAS", "cantidad": 2, "precio": 1.20, "costo": 0.60 },
    { "codigo": 7, "descripcion": "PAQUETE DE CLIP", "cantidad": 2, "precio": 0.90, "costo": 0.50 },
    { "codigo": 8, "descripcion": "PAQUETE ALFILERES ESCOLARES CHINCHE", "cantidad": 2, "precio": 0.90, "costo": 0.50 },
    { "codigo": 9, "descripcion": "MARCADOR PERMANETE DOBLE PUNTA", "cantidad": 17, "precio": 0.50, "costo": 0.30 },
    { "codigo": 10, "descripcion": "MARCADOR ACRILICO ECONOMICO", "cantidad": 27, "precio": 0.50, "costo": 0.30 },
    { "codigo": 11, "descripcion": "RECARGA", "cantidad": 0, "precio": 0, "costo": 0 },
    { "codigo": 12, "descripcion": "IMPRESIÓN", "cantidad": 0, "precio": 0, "costo": 0 },
    { "codigo": 15, "descripcion": "PLASTILINA 6 UND MODELING", "cantidad": 19, "precio": 0.45, "costo": 0.20 },
    { "codigo": 16, "descripcion": "PLASTILINA 10 UND GRANDE", "cantidad": 9, "precio": 0.70, "costo": 0.30 },
    { "codigo": 17, "descripcion": "TIZA DE COLORES CAJA", "cantidad": 8, "precio": 1.00, "costo": 0.60 },
    { "codigo": 18, "descripcion": "TIZA BLANCA CAJA", "cantidad": 12, "precio": 0.70, "costo": 0.30 },
    { "codigo": 19, "descripcion": "COLORES CERA 6 UND", "cantidad": 5, "precio": 0.35, "costo": 0.10 },
    { "codigo": 20, "descripcion": "COLORES CERA 12 UND", "cantidad": 5, "precio": 0.70, "costo": 0.40 },
    { "codigo": 21, "descripcion": "COLORES FAMOZOZ 12 UND", "cantidad": 5, "precio": 1.30, "costo": 0.85 },
    { "codigo": 22, "descripcion": "COLORES PASTELES CRISVI 12UND", "cantidad": 4, "precio": 1.50, "costo": 1.00 },
    { "codigo": 23, "descripcion": "COLORES MAKSIM 12 UND", "cantidad": 2, "precio": 1.40, "costo": 1.00 },
    { "codigo": 24, "descripcion": "KIT PORTAMINA 6 PIEZAS", "cantidad": 8, "precio": 1.50, "costo": 0.80 },
    { "codigo": 25, "descripcion": "RESALTADOR DELGADO 6 UND", "cantidad": 7, "precio": 1.60, "costo": 0.85 },
    { "codigo": 26, "descripcion": "MARCADOR ARTEZA 6 UND", "cantidad": 3, "precio": 0.70, "costo": 0.30 },
    { "codigo": 27, "descripcion": "CAJA MARCADOR WEIBO 12 DOBLE P", "cantidad": 5, "precio": 2.50, "costo": 1.45 },
    { "codigo": 28, "descripcion": "RESALTADOR CUADRADO KEIROAD 4 UND", "cantidad": 6, "precio": 2.10, "costo": 1.55 },
    { "codigo": 29, "descripcion": "KIT MARACADOR + BORRADOR ACRILICO", "cantidad": 6, "precio": 1.80, "costo": 1.00 },
    { "codigo": 30, "descripcion": "CARTUCHERA 3 D", "cantidad": 1, "precio": 2.50, "costo": 1.80 },
    { "codigo": 31, "descripcion": "CARTUCHERAS PLASTICAS", "cantidad": 8, "precio": 0.60, "costo": 0.30 },
    { "codigo": 32, "descripcion": "CARTILLAS ESCOLAR", "cantidad": 2, "precio": 1.00, "costo": 0.80 },
    { "codigo": 33, "descripcion": "EXACTO", "cantidad": 10, "precio": 0.30, "costo": 0.10 },
    { "codigo": 34, "descripcion": "LIMPIA PIPA TRADICIONAL", "cantidad": 2, "precio": 2.00, "costo": 1.50 },
    { "codigo": 35, "descripcion": "LIMPIA PIPA PELUDO", "cantidad": 1, "precio": 2.40, "costo": 1.70 },
    { "codigo": 36, "descripcion": "POMPONES", "cantidad": 1, "precio": 2.40, "costo": 1.70 },
    { "codigo": 37, "descripcion": "BOLSA TRANSPARENTE", "cantidad": 0, "precio": 1.80, "costo": 1.00 },
    { "codigo": 38, "descripcion": "PISTOLA DE SILICON", "cantidad": 1, "precio": 3.60, "costo": 2.40 },
    { "codigo": 39, "descripcion": "RESALTADOR 4 UND", "cantidad": 6, "precio": 1.50, "costo": 0.90 },
    { "codigo": 40, "descripcion": "MARCADOR YUECAI 10 UND", "cantidad": 10, "precio": 1.70, "costo": 1.10 },
    { "codigo": 41, "descripcion": "TIJERAS DAVEY", "cantidad": 6, "precio": 1.70, "costo": 1.10 },
    { "codigo": 101, "descripcion": "PAPEL BOND", "cantidad": 150, "precio": 0.30, "costo": 0.14 },
    { "codigo": 102, "descripcion": "CARTULINA DE COLORES", "cantidad": 68, "precio": 0.70, "costo": 0.35 },
    { "codigo": 103, "descripcion": "FOAMI UNICOLOR CARTA", "cantidad": 210, "precio": 0.25, "costo": 0.15 },
    { "codigo": 104, "descripcion": "FOAMI UNICOLOR DOBLE CARTA", "cantidad": 120, "precio": 0.45, "costo": 0.25 },
    { "codigo": 105, "descripcion": "FOAMI ESCARCHA CARTA", "cantidad": 206, "precio": 0.40, "costo": 0.25 },
    { "codigo": 106, "descripcion": "FOAMI ESCARCHA DOBLE CARTA", "cantidad": 117, "precio": 0.60, "costo": 0.40 },
    { "codigo": 107, "descripcion": "RESMA DE HOJA CARTA BLANCA 500 UND", "cantidad": 1, "precio": 7.00, "costo": 5.00 },
    { "codigo": 108, "descripcion": "MEDIA RESMA DE HOJA BLANCA 250 UND", "cantidad": 2, "precio": 4.00, "costo": 2.50 },
    { "codigo": 109, "descripcion": "HOJAS BLANCA UND 4*5BS", "cantidad": 335, "precio": 0.008, "costo": 0.004 },
    { "codigo": 110, "descripcion": "RESMA DE HOJA OFICIO", "cantidad": 0, "precio": 0, "costo": 0 },
    { "codigo": 111, "descripcion": "MEDIA RESMA DE HOJA BLANCA OFICIO 250 UND", "cantidad": 0, "precio": 0, "costo": 0 },
    { "codigo": 112, "descripcion": "HOJA OFICIO BLANCA UND 3*5BS", "cantidad": 150, "precio": 0.008, "costo": 0.004 },
    { "codigo": 113, "descripcion": "RESMA DE HOJA DE EXAMEN", "cantidad": 0, "precio": 0, "costo": 0 },
    { "codigo": 114, "descripcion": "HOJA DE EXAMEN UND 4 BS", "cantidad": 250, "precio": 0.06, "costo": 0.04 },
    { "codigo": 115, "descripcion": "CARTULINA ESCARCHADA PLIEGO", "cantidad": 20, "precio": 1.20, "costo": 0.70 },
    { "codigo": 116, "descripcion": "CARTULINA FLUORESCENTE PLIEGO", "cantidad": 12, "precio": 0.90, "costo": 0.50 },
    { "codigo": 117, "descripcion": "CARTULINA METALIZADA PLIEGO", "cantidad": 34, "precio": 1.20, "costo": 0.70 },
    { "codigo": 118, "descripcion": "CARTULINA DOBLE FAX PLIEGO PEQUEÑA", "cantidad": 20, "precio": 1.00, "costo": 0.55 },
    { "codigo": 119, "descripcion": "CARTULINA DOBLE FAX PLIEGO GRANDE", "cantidad": 12, "precio": 1.20, "costo": 0.70 },
    { "codigo": 120, "descripcion": "CARTULINA BLANCA ESCOLAR Y COLOR", "cantidad": 31, "precio": 0.50, "costo": 0.30 },
    { "codigo": 121, "descripcion": "PAPEL GREPPE", "cantidad": 170, "precio": 0.40, "costo": 0.20 },
    { "codigo": 122, "descripcion": "BLOCK MILIMETRADO 20 HOJAS", "cantidad": 6, "precio": 1.60, "costo": 1.00 },
    { "codigo": 123, "descripcion": "HOJA MILIMETRADO", "cantidad": 60, "precio": 0.10, "costo": 0.05 },
    { "codigo": 124, "descripcion": "TALONARIO DE FACTURAS N1", "cantidad": 3, "precio": 1.30, "costo": 0.70 },
    { "codigo": 125, "descripcion": "FICHA CRISVI 4X6 5 UND", "cantidad": 20, "precio": 0.20, "costo": 0.10 },
    { "codigo": 126, "descripcion": "FICHA CRISVI 5X8 5 UND", "cantidad": 20, "precio": 0.30, "costo": 0.15 },
    { "codigo": 127, "descripcion": "HOJA COLORES CARTA NEON", "cantidad": 45, "precio": 0.06, "costo": 0.04 },
    { "codigo": 128, "descripcion": "BLOCK CARTULINA COLORES", "cantidad": 6, "precio": 2.50, "costo": 1.50 },
    { "codigo": 129, "descripcion": "BLOCK DE CONSTRUCCION", "cantidad": 12, "precio": 0.95, "costo": 0.46 },
    { "codigo": 130, "descripcion": "BLOCK PAPEL LUSTRILLO", "cantidad": 16, "precio": 1.50, "costo": 1.00 },
    { "codigo": 131, "descripcion": "CARPETA LIGA UNICOLOR", "cantidad": 8, "precio": 1.50, "costo": 1.00 },
    { "codigo": 132, "descripcion": "CARPETA LIGA ESTANPADA", "cantidad": 12, "precio": 1.50, "costo": 1.00 },
    { "codigo": 133, "descripcion": "CARPETA NEON CARTA", "cantidad": 8, "precio": 0.60, "costo": 0.30 },
    { "codigo": 134, "descripcion": "LIBRO MI JARDIN", "cantidad": 6, "precio": 2.80, "costo": 1.50 },
    { "codigo": 135, "descripcion": "FUNDA PROTECTORA OFICIO", "cantidad": 20, "precio": 0.20, "costo": 0.10 },
    { "codigo": 136, "descripcion": "CARPETA MARRON CARTA", "cantidad": 24, "precio": 0.55, "costo": 0.30 },
    { "codigo": 137, "descripcion": "CARPETA MARON OFICIO", "cantidad": 25, "precio": 0.65, "costo": 0.35 },
    { "codigo": 138, "descripcion": "CARPETA AMARILLA CARTA", "cantidad": 0, "precio": 0, "costo": 0 },
    { "codigo": 139, "descripcion": "CARPETA AMARILLA OFICIO", "cantidad": 0, "precio": 0, "costo": 0 },
    { "codigo": 140, "descripcion": "LIBRETA 5 MATERIA", "cantidad": 6, "precio": 6.00, "costo": 3.30 },
    { "codigo": 141, "descripcion": "TEMPERA OSI", "cantidad": 3, "precio": 2.00, "costo": 1.50 },
    { "codigo": 142, "descripcion": "COMPAS POINTER", "cantidad": 6, "precio": 1.50, "costo": 0.90 },
    { "codigo": 143, "descripcion": "SILICON EN BARRA DELGADO", "cantidad": 73, "precio": 0.25, "costo": 0.12 },
    { "codigo": 144, "descripcion": "SILICON EN BARRA GRUESO", "cantidad": 51, "precio": 0.40, "costo": 0.20 },
    { "codigo": 145, "descripcion": "PALETA COLORES", "cantidad": 5, "precio": 0.70, "costo": 0.35 },
    { "codigo": 146, "descripcion": "PALETAS MARRON", "cantidad": 12, "precio": 0.70, "costo": 0.32 },
    { "codigo": 147, "descripcion": "MINAS", "cantidad": 48, "precio": 0.20, "costo": 0.10 },
    { "codigo": 148, "descripcion": "BORRADOR FABER CASTELLAN", "cantidad": 20, "precio": 0.30, "costo": 0.08 },
    { "codigo": 149, "descripcion": "BORRADOR CRISVI", "cantidad": 20, "precio": 0.30, "costo": 0.10 },
    { "codigo": 150, "descripcion": "SACAPUNTAS GRANDE CON DEPOSITO 2", "cantidad": 5, "precio": 0.55, "costo": 0.30 },
    { "codigo": 151, "descripcion": "SACAPUNTAS CON BORRADOR", "cantidad": 19, "precio": 0.55, "costo": 0.30 },
    { "codigo": 152, "descripcion": "GANCHOS PARA CARPETA", "cantidad": 30, "precio": 0.20, "costo": 0.05 },
    { "codigo": 153, "descripcion": "SACAPUNTAS DE HIERRO", "cantidad": 48, "precio": 0.25, "costo": 0.09 },
    { "codigo": 154, "descripcion": "ENGRAPADORA PEQUEÑA", "cantidad": 4, "precio": 2.70, "costo": 1.50 },
    { "codigo": 155, "descripcion": "PORTAMINAS", "cantidad": 19, "precio": 0.90, "costo": 0.50 },
    { "codigo": 156, "descripcion": "REGLAS POINTER", "cantidad": 6, "precio": 0.90, "costo": 0.50 },
    { "codigo": 157, "descripcion": "REGLA ECONOMICA", "cantidad": 19, "precio": 0.60, "costo": 0.30 },
    { "codigo": 158, "descripcion": "LAPIZ POINTER Y CRISVI", "cantidad": 82, "precio": 0.30, "costo": 0.15 },
    { "codigo": 159, "descripcion": "LAPIZ MONGOL", "cantidad": 60, "precio": 0.38, "costo": 0.20 },
    { "codigo": 160, "descripcion": "CORRECTOR TIPO LAPIZ", "cantidad": 12, "precio": 0.60, "costo": 0.30 },
    { "codigo": 161, "descripcion": "PINCEL ECONOMICO", "cantidad": 34, "precio": 0.25, "costo": 0.10 },
    { "codigo": 162, "descripcion": "LAPIZ BICOLOR", "cantidad": 12, "precio": 0.40, "costo": 0.20 },
    { "codigo": 163, "descripcion": "LAPICERO POINTER", "cantidad": 21, "precio": 0.30, "costo": 0.15 },
    { "codigo": 164, "descripcion": "ESCARCHA POTE", "cantidad": 36, "precio": 0.55, "costo": 0.25 },
    { "codigo": 165, "descripcion": "CINTA ESCOLAR", "cantidad": 9, "precio": 0.50, "costo": 0.20 },
    { "codigo": 166, "descripcion": "PEGA STICK KAISUO", "cantidad": 20, "precio": 0.60, "costo": 0.30 },
    { "codigo": 167, "descripcion": "SILICON LIQUIDO 60 ML REGIONAL DEPOT", "cantidad": 7, "precio": 1.20, "costo": 0.80 },
    { "codigo": 168, "descripcion": "PEGA BLANCA 120 ML REGIONAL", "cantidad": 5, "precio": 0.95, "costo": 0.50 },
    { "codigo": 169, "descripcion": "PEGA BLANCA 60ML REGIONAL", "cantidad": 18, "precio": 0.80, "costo": 0.40 },
    { "codigo": 170, "descripcion": "PEGA BLANCA 40 ML REGIONAL", "cantidad": 24, "precio": 0.60, "costo": 0.30 },
    { "codigo": 171, "descripcion": "PAPEL SEDA", "cantidad": 194, "precio": 0.20, "costo": 0.10 },
    { "codigo": 172, "descripcion": "PAPEL SEDA CON DETALLE", "cantidad": 20, "precio": 0.10, "costo": 0.10 },
    { "codigo": 173, "descripcion": "PAPEL CELOFAN TRANSPARENTE", "cantidad": 15, "precio": 0.80, "costo": 0.30 },
    { "codigo": 174, "descripcion": "CUADERNO VARIOS", "cantidad": 57, "precio": 1.00, "costo": 0.70 },
    { "codigo": 175, "descripcion": "LIBRETA 1 MATERIA", "cantidad": 21, "precio": 1.30, "costo": 0.85 },
    { "codigo": 176, "descripcion": "ANIME", "cantidad": 9, "precio": 2.80, "costo": 1.50 },
    { "codigo": 178, "descripcion": "PINTURA AL FRIO", "cantidad": 163, "precio": 0.80, "costo": 0.45 },
    { "codigo": 179, "descripcion": "LAPICERO DE GEL POINTER", "cantidad": 47, "precio": 0.65, "costo": 0.30 },
    { "codigo": 180, "descripcion": "BOLIGRAFO SEMIGEL", "cantidad": 26, "precio": 0.65, "costo": 0.40 },
    { "codigo": 181, "descripcion": "SOBRE MANILA CARTA", "cantidad": 31, "precio": 0.50, "costo": 0.20 },
    { "codigo": 182, "descripcion": "CINTA PARA EMBALAR", "cantidad": 0, "precio": 0, "costo": 0 },
    { "codigo": 183, "descripcion": "GRAPAS LISAS", "cantidad": 0, "precio": 0, "costo": 0 },
    { "codigo": 184, "descripcion": "BOLSO MARCADOR BLANCO 60 UND", "cantidad": 6, "precio": 8.12, "costo": 5.78 },
    { "codigo": 185, "descripcion": "CARTULINA METALIZADA TORNASOL", "cantidad": 12, "precio": 1.00, "costo": 0.50 },
    { "codigo": 186, "descripcion": "BOLSO MARCADORES NEGRO 36 UND", "cantidad": 7, "precio": 5.00, "costo": 3.30 },
    { "codigo": 187, "descripcion": "PINCEL DE MADERA", "cantidad": 12, "precio": 0.40, "costo": 0.20 },
    { "codigo": 188, "descripcion": "ESTAMBRE", "cantidad": 8, "precio": 0.65, "costo": 0.35 },
    { "codigo": 201, "descripcion": "RUBOR TRADICIONAL", "cantidad": 3, "precio": 1.60, "costo": 1.00 },
    { "codigo": 202, "descripcion": "REMOVEDOR DE PESTAÑAS", "cantidad": 3, "precio": 1.10, "costo": 0.60 },
    { "codigo": 203, "descripcion": "ILUMINADOR LABIAL", "cantidad": 1, "precio": 1.00, "costo": 0.60 },
    { "codigo": 204, "descripcion": "CORRECTOR LAPIZ", "cantidad": 1, "precio": 0.70, "costo": 0.50 },
    { "codigo": 205, "descripcion": "RUBOR+ SOMBRA", "cantidad": 1, "precio": 3.60, "costo": 2.50 },
    { "codigo": 206, "descripcion": "MINI PALETA SOMBRA", "cantidad": 5, "precio": 1.60, "costo": 0.95 },
    { "codigo": 207, "descripcion": "CONTORNO PARA OJOS", "cantidad": 6, "precio": 1.30, "costo": 0.75 },
    { "codigo": 301, "descripcion": "COMPACTO MONREVE", "cantidad": 14, "precio": 1.50, "costo": 0.99 },
    { "codigo": 302, "descripcion": "COMPACTO NAILEN", "cantidad": 10, "precio": 1.00, "costo": 0.70 },
    { "codigo": 303, "descripcion": "COMPACTO WINCOLOR", "cantidad": 14, "precio": 1.00, "costo": 0.60 },
    { "codigo": 304, "descripcion": "SEMI ELLYS NAII", "cantidad": 3, "precio": 1.70, "costo": 1.12 },
    { "codigo": 305, "descripcion": "SEMI MOMBRAY LAZO", "cantidad": 24, "precio": 1.60, "costo": 0.90 },
    { "codigo": 306, "descripcion": "SEMI MOMBRAY BASE", "cantidad": 13, "precio": 1.70, "costo": 1.10 },
    { "codigo": 307, "descripcion": "BASE RUBBER MOMBRAY", "cantidad": 6, "precio": 1.60, "costo": 1.00 },
    { "codigo": 308, "descripcion": "NUDE MOMBRAY", "cantidad": 4, "precio": 1.70, "costo": 1.10 },
    { "codigo": 309, "descripcion": "BASE COAT MOMBRAY LAZO", "cantidad": 10, "precio": 1.60, "costo": 0.90 },
    { "codigo": 310, "descripcion": "TOP COAT MOMBRAY LAZO", "cantidad": 11, "precio": 1.60, "costo": 0.90 },
    { "codigo": 311, "descripcion": "FINISH GEL MOMBRAY DORADA", "cantidad": 11, "precio": 1.70, "costo": 1.00 },
    { "codigo": 312, "descripcion": "RUBBER TRANSPARENTE MOMBRAY", "cantidad": 4, "precio": 1.50, "costo": 0.90 },
    { "codigo": 313, "descripcion": "6 EN 1 MOMBRAY", "cantidad": 1, "precio": 1.60, "costo": 0.90 },
    { "codigo": 314, "descripcion": "SEMI ELLYS NAIL NEGRA", "cantidad": 5, "precio": 1.70, "costo": 1.20 },
    { "codigo": 315, "descripcion": "RUBBER BASE M Y", "cantidad": 3, "precio": 1.50, "costo": 1.00 },
    { "codigo": 316, "descripcion": "ESMALTE MAXEL TRADICIONAL", "cantidad": 61, "precio": 1.05, "costo": 0.67 },
    { "codigo": 317, "descripcion": "ESMALTE VARIOS", "cantidad": 12, "precio": 0.60, "costo": 0.40 },
    { "codigo": 318, "descripcion": "ESMALTE MOMBRAY TRADICIONAL", "cantidad": 73, "precio": 1.05, "costo": 0.50 },
    { "codigo": 319, "descripcion": "RELOJ REDONDO COLORES", "cantidad": 5, "precio": 3.00, "costo": 1.50 },
    { "codigo": 320, "descripcion": "RELOJ CUADRADO COLORES", "cantidad": 0, "precio": 1.70, "costo": 0 },
    { "codigo": 321, "descripcion": "MAYA DONAS", "cantidad": 4, "precio": 1.00, "costo": 0.55 },
    { "codigo": 322, "descripcion": "COMPACTO MEILIS", "cantidad": 2, "precio": 1.40, "costo": 0.90 },
    { "codigo": 323, "descripcion": "NAVAJA ACERO BARBERIA ROJA AZUL", "cantidad": 1, "precio": 2.90, "costo": 1.80 },
    { "codigo": 324, "descripcion": "CERA PARA CABELLO VANGINS", "cantidad": 11, "precio": 2.50, "costo": 1.10 },
    { "codigo": 325, "descripcion": "BROCHA BARBERIA", "cantidad": 0, "precio": 1.00, "costo": 0 },
    { "codigo": 326, "descripcion": "ENVASE SPRAY BARBERIA", "cantidad": 0, "precio": 0.65, "costo": 0 },
    { "codigo": 327, "descripcion": "MAQUINA DE BARBA MEILIS", "cantidad": 0, "precio": 5.00, "costo": 0 },
    { "codigo": 328, "descripcion": "NAVAJA ACERO SALON CLIP", "cantidad": 0, "precio": 2.45, "costo": 0 },
    { "codigo": 329, "descripcion": "COMBO PEINE BARBERIA PLASTICO NEGRO 5 UND", "cantidad": 3, "precio": 3.50, "costo": 2.60 },
    { "codigo": 330, "descripcion": "PERFUME TUBITO 35ML DAMA CABALLERO NIÑO", "cantidad": 48, "precio": 1.35, "costo": 0.85 },
    { "codigo": 331, "descripcion": "PERFUME SPLAS 52ML", "cantidad": 4, "precio": 1.40, "costo": 0.90 },
    { "codigo": 332, "descripcion": "CREMA PERFUMADA CABALLERO 85ML", "cantidad": 1, "precio": 1.00, "costo": 0.70 },
    { "codigo": 333, "descripcion": "PERFUME CUADRADA CABALLERO 60 ML", "cantidad": 8, "precio": 2.60, "costo": 1.45 },
    { "codigo": 334, "descripcion": "SEMI TIFANNY", "cantidad": 14, "precio": 1.45, "costo": 0.80 },
    { "codigo": 335, "descripcion": "RELOJ DE CABALLERO NEGRO CASUAL", "cantidad": 0, "precio": 2.50, "costo": 0 },
    { "codigo": 336, "descripcion": "CARTERA DE CABALLERO BOTON", "cantidad": 3, "precio": 3.50, "costo": 1.87 },
    { "codigo": 337, "descripcion": "MINI ORGANIZADOR CABALLERO", "cantidad": 0, "precio": 3.10, "costo": 2.00 },
    { "codigo": 338, "descripcion": "PORTA CARNET CABALLERO LLAVERO", "cantidad": 0, "precio": 0.90, "costo": 0 },
    { "codigo": 339, "descripcion": "LAKA PARA CABALLERO", "cantidad": 1, "precio": 2.60, "costo": 1.87 },
    { "codigo": 340, "descripcion": "SPRAY BARBER SHOP", "cantidad": 4, "precio": 3.60, "costo": 2.50 },
    { "codigo": 341, "descripcion": "CREMA PERFUMADA DAMA 236 ML", "cantidad": 8, "precio": 1.60, "costo": 0.70 },
    { "codigo": 342, "descripcion": "CORREAS DE DAMA", "cantidad": 4, "precio": 3.00, "costo": 2.00 },
    { "codigo": 343, "descripcion": "MINI MONEDERO DAMA CIERRE", "cantidad": 2, "precio": 2.10, "costo": 1.45 },
    { "codigo": 344, "descripcion": "MINI MONEDERO DAMA BOTON", "cantidad": 2, "precio": 1.95, "costo": 1.35 },
    { "codigo": 345, "descripcion": "TIJERA PELUQUERIA PROFESIONAL", "cantidad": 2, "precio": 6.10, "costo": 4.30 },
    { "codigo": 346, "descripcion": "TIJERA PELUQUERIA ECONOMICA", "cantidad": 0, "precio": 1.40, "costo": 0 },
    { "codigo": 347, "descripcion": "CAPA DE BARBERIA PEQUEÑO", "cantidad": 3, "precio": 2.60, "costo": 1.50 },
    { "codigo": 348, "descripcion": "COMBO COLONIA MINI 2", "cantidad": 0, "precio": 1.00, "costo": 0 },
    { "codigo": 349, "descripcion": "COMBO COLONIA MINI 3", "cantidad": 0, "precio": 1.35, "costo": 0 },
    { "codigo": 350, "descripcion": "IMAN CRUZ 5 EN 1", "cantidad": 6, "precio": 4.00, "costo": 3.00 },
    { "codigo": 351, "descripcion": "PINTURA OJO E GATO", "cantidad": 6, "precio": 2.30, "costo": 1.70 },
    { "codigo": 352, "descripcion": "GEL DE CONSTRUCCION", "cantidad": 5, "precio": 1.95, "costo": 1.40 },
    { "codigo": 353, "descripcion": "SPLASH MONBRAY", "cantidad": 1, "precio": 4.00, "costo": 3.00 },
    { "codigo": 354, "descripcion": "HOJILLA DE CERAMICA", "cantidad": 5, "precio": 4.10, "costo": 2.50 },
    { "codigo": 355, "descripcion": "ACEITE DE MAQUINA", "cantidad": 5, "precio": 0.55, "costo": 0.20 },
    { "codigo": 356, "descripcion": "COLONIA EN ACEITE", "cantidad": 0, "precio": 2.60, "costo": 0 },
    { "codigo": 357, "descripcion": "COLONIA SPLASH INFANTIL", "cantidad": 2, "precio": 1.25, "costo": 0.85 },
    { "codigo": 358, "descripcion": "AFTER SHAVE \"A\"", "cantidad": 3, "precio": 5.00, "costo": 3.45 },
    { "codigo": 359, "descripcion": "AFTER SHAVE \"B\"", "cantidad": 3, "precio": 7.00, "costo": 4.55 },
    { "codigo": 360, "descripcion": "CUELLERA DE SILICON \"A\"", "cantidad": 3, "precio": 4.00, "costo": 2.45 },
    { "codigo": 361, "descripcion": "CUELLERA DE SILICON \"B\"", "cantidad": 3, "precio": 5.80, "costo": 3.45 },
    { "codigo": 362, "descripcion": "LACA BARBERIA \"A\"", "cantidad": 3, "precio": 4.00, "costo": 2.80 },
    { "codigo": 363, "descripcion": "LACA BARBERIA \"B\"", "cantidad": 3, "precio": 5.00, "costo": 3.70 },
    { "codigo": 364, "descripcion": "CERA KOMESIC \"A\"", "cantidad": 3, "precio": 2.40, "costo": 1.40 },
    { "codigo": 365, "descripcion": "CERA KOMESIC \"B\"", "cantidad": 3, "precio": 3.10, "costo": 2.40 },
    { "codigo": 366, "descripcion": "RELOJ YUROMI", "cantidad": 4, "precio": 2.10, "costo": 1.25 },
    { "codigo": 367, "descripcion": "PERFUME CABALLERO 100ML", "cantidad": 3, "precio": 3.40, "costo": 2.30 },
    { "codigo": 368, "descripcion": "HOJILLA DORCO CAJITA *5", "cantidad": 3, "precio": 0.75, "costo": 0.28 },
    { "codigo": 369, "descripcion": "HOJILLA DORCO UND", "cantidad": 30, "precio": 0.20, "costo": 0.10 },
    { "codigo": 370, "descripcion": "AGUJA PINZA PARA EXTENSIONES", "cantidad": 5, "precio": 0.85, "costo": 0.25 },
    { "codigo": 371, "descripcion": "GLITTER PARA UÑAS", "cantidad": 11, "precio": 0.70, "costo": 0.30 },
    { "codigo": 372, "descripcion": "COMPACTO + CONTORNO", "cantidad": 0, "precio": 1.50, "costo": 1.20 },
    { "codigo": 373, "descripcion": "COMPACTO FITME", "cantidad": 1, "precio": 1.00, "costo": 0.80 },
    { "codigo": 378, "descripcion": "ACEITE PARA CUTICULA", "cantidad": 0, "precio": 1.00, "costo": 0.50 },
    { "codigo": 379, "descripcion": "PRIMER PARA UÑAS MONBRAY", "cantidad": 4, "precio": 1.50, "costo": 0.80 },
    { "codigo": 380, "descripcion": "BLOSSOM GEL", "cantidad": 6, "precio": 1.70, "costo": 1.20 },
    { "codigo": 381, "descripcion": "PROTEIN BOND", "cantidad": 3, "precio": 1.80, "costo": 1.20 },
    { "codigo": 382, "descripcion": "REMOVEDOR SEMI", "cantidad": 2, "precio": 1.70, "costo": 1.05 },
    { "codigo": 383, "descripcion": "SEMI PURE LAZO", "cantidad": 2, "precio": 1.80, "costo": 1.18 },
    { "codigo": 384, "descripcion": "TOP COAT FINISH MAXGLOW", "cantidad": 3, "precio": 2.30, "costo": 1.70 },
    { "codigo": 385, "descripcion": "SEMI CON ESCARCHA DORADA", "cantidad": 2, "precio": 2.35, "costo": 1.60 },
    { "codigo": 389, "descripcion": "PINTURA CHINA BLANCA", "cantidad": 7, "precio": 0.40, "costo": 0.20 },
    { "codigo": 390, "descripcion": "SEMI VARIAS", "cantidad": 13, "precio": 1.40, "costo": 1.00 },
    { "codigo": 391, "descripcion": "LOCION PERFUMADA 150ML", "cantidad": 12, "precio": 1.00, "costo": 0.60 },
    { "codigo": 392, "descripcion": "RELOJ GRUESO", "cantidad": 1, "precio": 3.00, "costo": 2.00 },
    { "codigo": 393, "descripcion": "POLY GEL MONBRAY", "cantidad": 6, "precio": 2.70, "costo": 2.00 }
 { "codigo": 401, "descripcion": "BANDANA MAQUILLAJE JUVENIL", "cantidad": 6, "precio": 1.30, "costo": 0.85 },
    { "codigo": 402, "descripcion": "BANDANA GRUESA DAMA", "cantidad": 13, "precio": 1.00, "costo": 0.50 },
    { "codigo": 403, "descripcion": "CINTILLO NUBE DAMA", "cantidad": 6, "precio": 3.00, "costo": 1.85 },
    { "codigo": 404, "descripcion": "COLITA COLORES 6 UND", "cantidad": 48, "precio": 0.45, "costo": 0.16 },
    { "codigo": 405, "descripcion": "COLITA COLORES LAZO 6 UND", "cantidad": 6, "precio": 0.60, "costo": 0.36 },
    { "codigo": 406, "descripcion": "COLITAS COLORES MINI 6 UND", "cantidad": 19, "precio": 0.40, "costo": 0.12 },
    { "codigo": 407, "descripcion": "PINZAS CLASICAS PAQ", "cantidad": 4, "precio": 0.90, "costo": 0.30 },
    { "codigo": 408, "descripcion": "PAQUETE DE COLITAS MINI 30 UND", "cantidad": 17, "precio": 1.20, "costo": 0.80 },
    { "codigo": 409, "descripcion": "PIOJITOS ARO 9 UND", "cantidad": 10, "precio": 0.90, "costo": 0.50 },
    { "codigo": 410, "descripcion": "PAQUETE PIOJITOS CROMADOS 30 UND", "cantidad": 4, "precio": 2.20, "costo": 1.45 },
    { "codigo": 411, "descripcion": "PAQUETE PIOJITOS MATE 30 UND", "cantidad": 5, "precio": 2.00, "costo": 1.00 },
    { "codigo": 412, "descripcion": "PINZA DORADA C/ PERLA", "cantidad": 9, "precio": 0.90, "costo": 0.50 },
    { "codigo": 413, "descripcion": "GRAPA P/ CABELLO BOLSITA 20 UND", "cantidad": 24, "precio": 0.50, "costo": 0.30 },
    { "codigo": 414, "descripcion": "GRAPA P/ CABELLO PLASTICO", "cantidad": 8, "precio": 1.10, "costo": 0.50 },
    { "codigo": 415, "descripcion": "PAQUETE COLITAS CLASICAS", "cantidad": 0, "precio": 1.10, "costo": 0.50 },
    { "codigo": 416, "descripcion": "PAQUETE COLITAS DECORADAS", "cantidad": 8, "precio": 1.30, "costo": 0.80 },
    { "codigo": 417, "descripcion": "PAQUETE DE COLITAS NEGRAS MINI", "cantidad": 3, "precio": 1.40, "costo": 0.75 },
    { "codigo": 418, "descripcion": "PAQUETE DE GANCHITOS CON COLAS", "cantidad": 0, "precio": 1.00, "costo": 0 },
    { "codigo": 419, "descripcion": "PAQUETE DE GANCHITOS NIÑAS", "cantidad": 2, "precio": 1.50, "costo": 1.00 },
    { "codigo": 420, "descripcion": "PAQUETE DE PINZA MINI 6 UND", "cantidad": 2, "precio": 1.00, "costo": 0.60 },
    { "codigo": 421, "descripcion": "PAQUETE DE PINZA FRUTAS NIÑA", "cantidad": 9, "precio": 0.80, "costo": 0.50 },
    { "codigo": 422, "descripcion": "STICKER PARA CABELLO", "cantidad": 14, "precio": 0.90, "costo": 0.50 },
    { "codigo": 423, "descripcion": "PAQUETE DE COLAS MEDIANA 36 UND", "cantidad": 2, "precio": 2.00, "costo": 1.50 },
    { "codigo": 424, "descripcion": "LIGAS COLORES NEON", "cantidad": 7, "precio": 0.65, "costo": 0.25 },
    { "codigo": 425, "descripcion": "LIGAS GRUESAS", "cantidad": 46, "precio": 0.50, "costo": 0.15 },
    { "codigo": 426, "descripcion": "LIGAS DELGADAS", "cantidad": 6, "precio": 0.45, "costo": 0.13 },
    { "codigo": 427, "descripcion": "GANCHOS LENTEJUELAS PAR", "cantidad": 4, "precio": 2.10, "costo": 0.75 },
    { "codigo": 428, "descripcion": "GANCHOS LENTEJUELAS UNIDAD", "cantidad": 0, "precio": 0.80, "costo": 0.40 },
    { "codigo": 429, "descripcion": "GANCHOS KUROMI PAQ PLASTICO", "cantidad": 2, "precio": 2.10, "costo": 1.35 },
    { "codigo": 430, "descripcion": "GANCHOS VARIOS PAQUETE", "cantidad": 7, "precio": 1.25, "costo": 0.67 },
    { "codigo": 431, "descripcion": "LLAVERO CON ESPEJO DAMA", "cantidad": 1, "precio": 1.00, "costo": 0.85 },
    { "codigo": 432, "descripcion": "PAÑOLETAS", "cantidad": 4, "precio": 1.10, "costo": 0.60 },
    { "codigo": 433, "descripcion": "BROCHA PARA TINTE", "cantidad": 1, "precio": 0.80, "costo": 0.40 },
    { "codigo": 434, "descripcion": "CEPILLO NEGRO CLASICO PEQUEÑO", "cantidad": 2, "precio": 3.20, "costo": 2.25 },
    { "codigo": 435, "descripcion": "CEPILLO P/ CABELLO CUADRADO", "cantidad": 3, "precio": 2.30, "costo": 1.25 },
    { "codigo": 436, "descripcion": "PEINE SACAPIOJO METAL", "cantidad": 2, "precio": 1.60, "costo": 1.00 },
    { "codigo": 437, "descripcion": "BORLAS MAQUILLAJE 4 UND", "cantidad": 2, "precio": 1.50, "costo": 0.85 },
    { "codigo": 438, "descripcion": "BORLAS MAQUILLAJE CORAZON 2 UND", "cantidad": 0, "precio": 0.65, "costo": 0 },
    { "codigo": 439, "descripcion": "UÑAS DECORADAS BONITO", "cantidad": 3, "precio": 1.50, "costo": 0.90 },
    { "codigo": 440, "descripcion": "UÑAS DE NIÑA KIT", "cantidad": 4, "precio": 1.60, "costo": 1.00 },
    { "codigo": 441, "descripcion": "UÑAS P/PIES 120 UND MOMBRAY", "cantidad": 2, "precio": 1.20, "costo": 0.67 },
    { "codigo": 442, "descripcion": "UÑAS JELLYS CUADRADA 100 UND MONBRAY", "cantidad": 0, "precio": 0.67, "costo": 0 },
    { "codigo": 443, "descripcion": "UÑAS JELLYS CUADRADAS 240 UND", "cantidad": 0, "precio": 1.78, "costo": 0 },
    { "codigo": 444, "descripcion": "PESTAÑAS MAC POR PUNTOS", "cantidad": 21, "precio": 1.00, "costo": 0.50 },
    { "codigo": 445, "descripcion": "UÑAS 3D", "cantidad": 2, "precio": 2.00, "costo": 1.50 },
    { "codigo": 446, "descripcion": "RIZADOR DE PESTAÑAS ECONOMICO", "cantidad": 1, "precio": 1.60, "costo": 1.00 },
    { "codigo": 447, "descripcion": "PERFILADOR DE CEJAS 3 UND", "cantidad": 11, "precio": 1.20, "costo": 0.67 },
    { "codigo": 448, "descripcion": "PALITOS DE NARANJA 50 UND", "cantidad": 5, "precio": 1.60, "costo": 1.00 },
    { "codigo": 449, "descripcion": "CEPILLO PARA CEJAS 50 UND", "cantidad": 4, "precio": 1.60, "costo": 1.00 },
    { "codigo": 450, "descripcion": "PALETA PARA PIES PLASTICA", "cantidad": 7, "precio": 1.20, "costo": 0.60 },
    { "codigo": 451, "descripcion": "GUILLOTINA PARA UÑAS ECONOMICA", "cantidad": 1, "precio": 1.10, "costo": 0.80 },
    { "codigo": 452, "descripcion": "BROCHA QUITA POLVO PARA UÑAS", "cantidad": 5, "precio": 1.10, "costo": 0.60 },
    { "codigo": 453, "descripcion": "SET DE BROCHA SIRENA MAQUILLAJE SET 3", "cantidad": 5, "precio": 1.55, "costo": 0.90 },
    { "codigo": 454, "descripcion": "GORRO TERMICO 1 UND", "cantidad": 2, "precio": 1.10, "costo": 0.67 },
    { "codigo": 455, "descripcion": "GORRO PARA PLANCHADO 2 UND", "cantidad": 7, "precio": 0.80, "costo": 0.30 },
    { "codigo": 456, "descripcion": "PINCEL LINER 3 UND", "cantidad": 2, "precio": 1.40, "costo": 0.70 },
    { "codigo": 457, "descripcion": "BOLSA REGALO MINI", "cantidad": 0, "precio": 0.20, "costo": 0 },
    { "codigo": 458, "descripcion": "EFECTO ESPEJO P/UNAS", "cantidad": 3, "precio": 2.20, "costo": 1.50 },
    { "codigo": 459, "descripcion": "SELLO P/UNAS TRANSPARENTE", "cantidad": 3, "precio": 1.00, "costo": 0.67 },
    { "codigo": 460, "descripcion": "CORTA CUTICULA PLASTICO", "cantidad": 5, "precio": 0.80, "costo": 0.37 },
    { "codigo": 461, "descripcion": "CORTA CUTICULA METAL ECONOMICO", "cantidad": 0, "precio": 1.00, "costo": 0 },
    { "codigo": 462, "descripcion": "PATA E CABRA P/ UNAS PAQUETE 5 UND", "cantidad": 2, "precio": 1.10, "costo": 0.80 },
    { "codigo": 463, "descripcion": "PIEDRA POME ECONOMICA", "cantidad": 5, "precio": 0.80, "costo": 0.30 },
    { "codigo": 464, "descripcion": "REPUJADOR P/ UNAS", "cantidad": 1, "precio": 0.60, "costo": 0.30 },
    { "codigo": 465, "descripcion": "GANCHOS NEGRO P/ CABELLO PEQ", "cantidad": 7, "precio": 0.85, "costo": 0.30 },
    { "codigo": 466, "descripcion": "MOSTRARIO PARA MANICURISTAS", "cantidad": 5, "precio": 2.10, "costo": 1.50 },
    { "codigo": 467, "descripcion": "KOALA UNIXES", "cantidad": 3, "precio": 2.50, "costo": 1.50 },
    { "codigo": 468, "descripcion": "BANDANA NEGRA DAMA", "cantidad": 0, "precio": 1.00, "costo": 0.50 },
    { "codigo": 469, "descripcion": "GORRO SATIN", "cantidad": 0, "precio": 0.80, "costo": 0 },
    { "codigo": 470, "descripcion": "COLITAS SATIN", "cantidad": 1, "precio": 0.80, "costo": 0.50 },
    { "codigo": 471, "descripcion": "CEPILLO PARA RIZOS", "cantidad": 5, "precio": 2.60, "costo": 1.50 },
    { "codigo": 472, "descripcion": "PEINE CABALLERO PEQ", "cantidad": 12, "precio": 0.50, "costo": 0.20 },
    { "codigo": 473, "descripcion": "ESPEJO REDONDO", "cantidad": 2, "precio": 1.60, "costo": 1.00 },
    { "codigo": 474, "descripcion": "CAPA BARBERIA IMPRESA", "cantidad": 4, "precio": 6.00, "costo": 4.50 },
    { "codigo": 475, "descripcion": "MARIPOSA CARNAVAL INFANTIL", "cantidad": 7, "precio": 3.00, "costo": 1.50 },
    { "codigo": 476, "descripcion": "DELANTAR MANICURISTA", "cantidad": 2, "precio": 5.50, "costo": 3.50 },
    { "codigo": 477, "descripcion": "GANCHOS DE DAMA COLORES", "cantidad": 5, "precio": 0.90, "costo": 0.30 },
    { "codigo": 478, "descripcion": "GORRA DE MARCA AAA", "cantidad": 6, "precio": 8.00, "costo": 6.00 },
    { "codigo": 479, "descripcion": "GORRA DE MARCA AA", "cantidad": 1, "precio": 7.60, "costo": 4.00 },
    { "codigo": 480, "descripcion": "GORRA INFANTIL", "cantidad": 2, "precio": 3.00, "costo": 2.00 },
    { "codigo": 481, "descripcion": "BOLSA REGALO PAPEL PEQ", "cantidad": 3, "precio": 0.50, "costo": 0.20 },
    { "codigo": 482, "descripcion": "BANDANA BEBE", "cantidad": 11, "precio": 1.40, "costo": 0.85 },
    { "codigo": 483, "descripcion": "BOLSA REGALO PAPEL 27*21 MEDIANA", "cantidad": 4, "precio": 0.85, "costo": 0.45 },
    { "codigo": 484, "descripcion": "BOLSA REGALO PAPEL NAVIDAD 27*21", "cantidad": 0, "precio": 0.45, "costo": 0 },
    { "codigo": 485, "descripcion": "UÑAS DE NIÑA 3D", "cantidad": 0, "precio": 0.58, "costo": 0 },
    { "codigo": 486, "descripcion": "UÑAS JELLY POROSIDAD TIFANY", "cantidad": 4, "precio": 2.20, "costo": 1.20 },
    { "codigo": 487, "descripcion": "UÑAS JELLY BAILARINA", "cantidad": 3, "precio": 3.60, "costo": 2.50 },
    { "codigo": 488, "descripcion": "PINZA PARA PLANCHADO", "cantidad": 6, "precio": 0.45, "costo": 0.20 },
    { "codigo": 489, "descripcion": "EXTENCION PARA NIÑA TRENZA", "cantidad": 7, "precio": 1.50, "costo": 0.85 },
    { "codigo": 490, "descripcion": "EXTENCION MULTICOLOR PARA NIÑA", "cantidad": 0, "precio": 0.85, "costo": 0 },
    { "codigo": 491, "descripcion": "MINI GANCHOS TORNASOL PAR", "cantidad": 0, "precio": 0.30, "costo": 0.00 },
    { "codigo": 492, "descripcion": "CINTILLO STICK", "cantidad": 2, "precio": 1.80, "costo": 0.85 },
    { "codigo": 493, "descripcion": "GORRO DE MALLA", "cantidad": 6, "precio": 0.90, "costo": 0.40 },
    { "codigo": 494, "descripcion": "GORRO SILICON P/MECHAS", "cantidad": 1, "precio": 7.60, "costo": 5.50 },
    { "codigo": 495, "descripcion": "GORRO DESECHABLE", "cantidad": 4, "precio": 1.10, "costo": 0.55 },
    { "codigo": 496, "descripcion": "UÑAS ALMENDRA 240UNS", "cantidad": 1, "precio": 3.70, "costo": 2.60 },
    { "codigo": 497, "descripcion": "UÑAS STILETO 120UND", "cantidad": 6, "precio": 2.20, "costo": 1.60 },
    { "codigo": 498, "descripcion": "PAQ DE GANCHO YUROMI", "cantidad": 4, "precio": 2.10, "costo": 1.35 },
    { "codigo": 499, "descripcion": "PINCEL LINER *3", "cantidad": 2, "precio": 1.00, "costo": 0.50 },
    { "codigo": 501, "descripcion": "PORTACOSMETICOS", "cantidad": 6, "precio": 3.30, "costo": 2.30 },
    { "codigo": 502, "descripcion": "BOLSO ESCOLAR DINOSAURIO 3 PIEZAS", "cantidad": 1, "precio": 13.00, "costo": 8.50 },
    { "codigo": 503, "descripcion": "BANDOLERO CABALLERO ECONOMICO", "cantidad": 1, "precio": 3.50, "costo": 1.80 },
    { "codigo": 504, "descripcion": "BANDOLERO CABALLERO LOGO ROJO", "cantidad": 0, "precio": 2.50, "costo": 0.00 },
    { "codigo": 505, "descripcion": "BANDOLERO CUADRADO CABALLEROS", "cantidad": 0, "precio": 4.00, "costo": 3.00 },
    { "codigo": 506, "descripcion": "BANDOLERO CUADRADO PEQ DAMA", "cantidad": 1, "precio": 6.00, "costo": 2.00 },
    { "codigo": 507, "descripcion": "BANDOLERO DAMA REDONDO", "cantidad": 1, "precio": 6.00, "costo": 4.00 },
    { "codigo": 508, "descripcion": "BANDOLERO MINI MARRON", "cantidad": 0, "precio": 1.80, "costo": 0.00 },
    { "codigo": 509, "descripcion": "MORRAL ESTAMPADO P/ DAMA", "cantidad": 1, "precio": 9.00, "costo": 6.00 },
    { "codigo": 510, "descripcion": "CONTORNO FACIAL MINI", "cantidad": 22, "precio": 1.00, "costo": 0.50 },
    { "codigo": 511, "descripcion": "LONCHERA TERMICA NIÑA", "cantidad": 1, "precio": 3.50, "costo": 2.00 },
    { "codigo": 512, "descripcion": "SOMBRA PARA OJOS LAMEILA", "cantidad": 6, "precio": 1.10, "costo": 0.85 },
    { "codigo": 513, "descripcion": "PALETA DE SOMBRA MUÑECA", "cantidad": 1, "precio": 5.10, "costo": 3.60 },
    { "codigo": 514, "descripcion": "PIGMENTOS PARA CEJAS M Y", "cantidad": 4, "precio": 1.50, "costo": 0.99 },
    { "codigo": 515, "descripcion": "PIGMENTO SUPER CRISTAL", "cantidad": 2, "precio": 4.60, "costo": 3.20 },
    { "codigo": 516, "descripcion": "SOBRE MASCARILLA FACIAL", "cantidad": 13, "precio": 0.65, "costo": 0.30 },
    { "codigo": 517, "descripcion": "SOBRE MASCARILLA FACIAL MEDIANA", "cantidad": 24, "precio": 0.75, "costo": 0.35 },
    { "codigo": 518, "descripcion": "SOBRE MASCARILLA PARA LABIOS", "cantidad": 11, "precio": 0.55, "costo": 0.20 },
    { "codigo": 519, "descripcion": "SOBRE MASCARILLA PARA OJERAS", "cantidad": 15, "precio": 0.55, "costo": 0.20 },
    { "codigo": 520, "descripcion": "MASCARILLA PUNTO NEGRO 3 PASOS", "cantidad": 11, "precio": 0.90, "costo": 0.50 },
    { "codigo": 521, "descripcion": "PROTECTOR SOLAR SPRAY GRENOBIL", "cantidad": 3, "precio": 2.90, "costo": 1.80 },
    { "codigo": 522, "descripcion": "PROTECTOR SOLAR BASE BIODERMA", "cantidad": 1, "precio": 2.10, "costo": 1.10 },
    { "codigo": 523, "descripcion": "ACEITE PARA CABELLO MASAJE TIFANNY", "cantidad": 6, "precio": 1.60, "costo": 0.85 },
    { "codigo": 524, "descripcion": "ESPUMA FACIAL LIMPIADORA 120ML", "cantidad": 2, "precio": 3.10, "costo": 1.80 },
    { "codigo": 525, "descripcion": "CREMA LIMPIADORA VITAMINA C 100ML", "cantidad": 1, "precio": 2.10, "costo": 1.00 },
    { "codigo": 526, "descripcion": "EXFOLAINTE FACIAL HUDABEAUTY", "cantidad": 2, "precio": 2.30, "costo": 1.50 },
    { "codigo": 527, "descripcion": "ESPONJA LIMPIADORA SKINCARE", "cantidad": 2, "precio": 1.00, "costo": 0.85 },
    { "codigo": 528, "descripcion": "DESMAQUILLANTE 60ML ROSADO", "cantidad": 6, "precio": 1.60, "costo": 1.00 },
    { "codigo": 529, "descripcion": "AGUA MISCELAR RIBIABEAUTY 100ML", "cantidad": 6, "precio": 2.10, "costo": 1.50 },
    { "codigo": 530, "descripcion": "CREMA LIMPIADORA DE COCO 50 ML", "cantidad": 1, "precio": 0.90, "costo": 0.50 },
    { "codigo": 531, "descripcion": "FIJADOR DE MAQUILAJE VITAMINA C 60 ML", "cantidad": 1, "precio": 2.10, "costo": 1.00 },
    { "codigo": 532, "descripcion": "SERUM 24K", "cantidad": 1, "precio": 0.80, "costo": 0.85 },
    { "codigo": 533, "descripcion": "PALETA SOMBRA CAT LADY", "cantidad": 6, "precio": 2.00, "costo": 1.50 },
    { "codigo": 534, "descripcion": "SERUM VARIOS", "cantidad": 7, "precio": 1.60, "costo": 1.00 },
    { "codigo": 535, "descripcion": "COLOR 1 NEGRO", "cantidad": 10, "precio": 1.40, "costo": 0.85 },
    { "codigo": 536, "descripcion": "BIGEN ECONOMICO", "cantidad": 11, "precio": 1.20, "costo": 0.85 },
    { "codigo": 537, "descripcion": "VASITO CRISTAL", "cantidad": 11, "precio": 0.60, "costo": 0.25 },
    { "codigo": 538, "descripcion": "CAJA TOALLAS", "cantidad": 3, "precio": 1.60, "costo": 1.00 },
    { "codigo": 539, "descripcion": "GEL FACIAL ALOE VERA Y PARA PESTANAS", "cantidad": 3, "precio": 2.10, "costo": 1.35 },
    { "codigo": 540, "descripcion": "PEGA SALOM PRO ORIGINAL", "cantidad": 4, "precio": 4.00, "costo": 2.90 },
    { "codigo": 541, "descripcion": "PEGA ARDELL ORIGINAL", "cantidad": 3, "precio": 7.10, "costo": 5.50 },
    { "codigo": 542, "descripcion": "PEGA SALOM PRO IMITACION", "cantidad": 0, "precio": 1.60, "costo": 0.85 },
    { "codigo": 546, "descripcion": "ESPONJA FASCIAL CON BORLA 3 PIEZAS", "cantidad": 0, "precio": 0.67, "costo": 0.00 },
    { "codigo": 547, "descripcion": "ESPONJA FACIAL 1 UND", "cantidad": 0, "precio": 0.30, "costo": 0.00 },
    { "codigo": 548, "descripcion": "ESPONJA FACIAL 3 UND", "cantidad": 14, "precio": 1.00, "costo": 0.60 },
    { "codigo": 552, "descripcion": "COLONIA MINI CABALLERO", "cantidad": 40, "precio": 0.50, "costo": 0.30 },
    { "codigo": 553, "descripcion": "PEGA ARDELL IMITACION", "cantidad": 5, "precio": 1.60, "costo": 0.95 },
    { "codigo": 554, "descripcion": "SOMBRA PARA OJOS 6 TONOS", "cantidad": 5, "precio": 1.50, "costo": 1.10 },
    { "codigo": 555, "descripcion": "SOMBRA PARA CEJAS 3 TONOS KEBOSI", "cantidad": 12, "precio": 1.30, "costo": 0.80 },
    { "codigo": 556, "descripcion": "SOMBRA PARA CEJAS + GEL", "cantidad": 2, "precio": 1.40, "costo": 1.00 },
    { "codigo": 557, "descripcion": "SOMBRA PARA CEJAS MISS FON CUADRADA", "cantidad": 4, "precio": 1.50, "costo": 0.85 },
    { "codigo": 558, "descripcion": "SOMBRA PARA CEJAS MANZANA", "cantidad": 6, "precio": 1.30, "costo": 0.80 },
    { "codigo": 559, "descripcion": "POMADA PARA CEJAS NUDE", "cantidad": 0, "precio": 1.00, "costo": 0.00 },
    { "codigo": 560, "descripcion": "CORRECTOR FACIAL HUXIABEAUTY", "cantidad": 20, "precio": 1.00, "costo": 0.50 },
    { "codigo": 561, "descripcion": "CORRECTOR BB FRESH", "cantidad": 12, "precio": 1.30, "costo": 0.80 },
    { "codigo": 562, "descripcion": "POLVO SUELTO MEIKE GLAMOUR", "cantidad": 3, "precio": 1.50, "costo": 0.85 },
    { "codigo": 563, "descripcion": "TOALLAS PAQ PEQ ROSADA", "cantidad": 6, "precio": 0.30, "costo": 0.15 },
    { "codigo": 564, "descripcion": "PINCEL PARA CEJAS 2 EN 1", "cantidad": 19, "precio": 0.85, "costo": 0.30 },
    { "codigo": 565, "descripcion": "PINCEL QUIRURGICO", "cantidad": 8, "precio": 1.60, "costo": 1.00 },
    { "codigo": 566, "descripcion": "TIJERA PARA CEJAS", "cantidad": 5, "precio": 1.50, "costo": 0.80 },
    { "codigo": 567, "descripcion": "ENVASE LAVA CEJAS", "cantidad": 3, "precio": 3.50, "costo": 2.50 },
    { "codigo": 568, "descripcion": "SET CON ESPEJO PARA CEJAS", "cantidad": 6, "precio": 1.00, "costo": 0.50 },
    { "codigo": 569, "descripcion": "BROCHA PARA CEJAS", "cantidad": 6, "precio": 1.50, "costo": 0.80 },
    { "codigo": 570, "descripcion": "ESPUMA LIMPIADORA P CEJAS", "cantidad": 2, "precio": 3.10, "costo": 2.00 },
    { "codigo": 571, "descripcion": "ENVOPLAST PARA CEJAS", "cantidad": 2, "precio": 1.60, "costo": 1.00 },
    { "codigo": 572, "descripcion": "VERNIER", "cantidad": 6, "precio": 2.10, "costo": 1.25 },
    { "codigo": 573, "descripcion": "LAPIZ DE CEJAS FASHION CAJA", "cantidad": 6, "precio": 0.90, "costo": 0.45 },
    { "codigo": 574, "descripcion": "MICROBLANDING", "cantidad": 23, "precio": 1.00, "costo": 0.50 },
    { "codigo": 575, "descripcion": "LAPIZ DE OJOS MAC", "cantidad": 39, "precio": 0.45, "costo": 0.20 },
    { "codigo": 576, "descripcion": "ESPONJA KISS PLUS 2 PIEZAS", "cantidad": 3, "precio": 2.10, "costo": 1.45 },
    { "codigo": 577, "descripcion": "ESPONJA KISS PLUS 3 PIEZAS", "cantidad": 1, "precio": 1.30, "costo": 0.85 },
    { "codigo": 578, "descripcion": "CERA BODY", "cantidad": 3, "precio": 3.30, "costo": 2.00 },
    { "codigo": 579, "descripcion": "CERA AZULENO", "cantidad": 3, "precio": 5.10, "costo": 4.00 },
    { "codigo": 580, "descripcion": "OLLA PARA CERA", "cantidad": 3, "precio": 12.50, "costo": 9.50 },
    { "codigo": 581, "descripcion": "BANDAS PARA DEPILAR", "cantidad": 3, "precio": 2.60, "costo": 1.60 },
    { "codigo": 582, "descripcion": "PALETAS PARA CERA 4 UND", "cantidad": 25, "precio": 0.30, "costo": 0.10 },
    { "codigo": 583, "descripcion": "GUANTES LATEX PAR", "cantidad": 45, "precio": 0.35, "costo": 0.17 },
    { "codigo": 584, "descripcion": "ALGODÓN MOPA PEQUEÑA", "cantidad": 4, "precio": 1.20, "costo": 0.60 },
    { "codigo": 585, "descripcion": "PALITOS DE NARANJA 3 UND", "cantidad": 15, "precio": 0.30, "costo": 0.06 },
    { "codigo": 586, "descripcion": "CEPILLO PARA CEJAS Y PESTAÑAS 3UND", "cantidad": 25, "precio": 0.30, "costo": 0.06 },
    { "codigo": 587, "descripcion": "ESPONJA UNIDAD BOLSITA", "cantidad": 0, "precio": 0.50, "costo": 0.25 },
    { "codigo": 588, "descripcion": "TOALLA FACIAL", "cantidad": 12, "precio": 1.00, "costo": 0.50 },
    { "codigo": 589, "descripcion": "PEINE DE LISTING", "cantidad": 50, "precio": 0.45, "costo": 0.20 },
    { "codigo": 590, "descripcion": "COLOR 1 MARRON", "cantidad": 11, "precio": 2.35, "costo": 1.75 },
    { "codigo": 591, "descripcion": "SOMBRA PARTY", "cantidad": 1, "precio": 1.80, "costo": 2.30 },
    { "codigo": 592, "descripcion": "DELINEADOR MARCADOR", "cantidad": 27, "precio": 0.80, "costo": 0.30 },
    { "codigo": 593, "descripcion": "MASCARILLA PUNTO NEGRO MILK", "cantidad": 3, "precio": 0.90, "costo": 0.50 },
    { "codigo": 594, "descripcion": "PALETA SOMBRA COLORES", "cantidad": 0, "precio": 4.20, "costo": 0.00 },
    { "codigo": 595, "descripcion": "CREMA POND ACLARANTE", "cantidad": 9, "precio": 1.60, "costo": 1.00 },
    { "codigo": 596, "descripcion": "LIMPIADORA PARA CEJAS", "cantidad": 6, "precio": 2.30, "costo": 1.20 },
    { "codigo": 597, "descripcion": "SOMBRA NEON", "cantidad": 2, "precio": 1.40, "costo": 1.00 },
    { "codigo": 598, "descripcion": "MICROBLANDING MARCADOR", "cantidad": 7, "precio": 1.00, "costo": 0.50 },
    { "codigo": 599, "descripcion": "ILUMINADOR EN BARRA", "cantidad": 4, "precio": 1.60, "costo": 1.00 },
    { "codigo": 601, "descripcion": "MASCARA PARA PESTANAS MAC 2 EN 1", "cantidad": 3, "precio": 2.00, "costo": 1.50 },
    { "codigo": 602, "descripcion": "DELINEADOR HUXIARBEATTET", "cantidad": 23, "precio": 1.00, "costo": 0.80 },
    { "codigo": 603, "descripcion": "MASCARA DE PESTANA +GEL PARA CEJAS", "cantidad": 2, "precio": 1.50, "costo": 1.00 },
    { "codigo": 604, "descripcion": "RIZADOR DE PESTANAS CROMADO", "cantidad": 3, "precio": 1.70, "costo": 1.00 },
    { "codigo": 605, "descripcion": "BASE FACIAL HUXIABEAUTY", "cantidad": 13, "precio": 0.90, "costo": 0.50 },
    { "codigo": 606, "descripcion": "BASE FACIAL COMFORT BEAUTY", "cantidad": 7, "precio": 0.90, "costo": 0.50 },
    { "codigo": 607, "descripcion": "LABIAL OSO", "cantidad": 23, "precio": 1.00, "costo": 0.60 },
    { "codigo": 608, "descripcion": "DELINEADOR LIQUIDO CROMADO", "cantidad": 22, "precio": 0.80, "costo": 0.30 },
    { "codigo": 609, "descripcion": "POLVO DE HADAS", "cantidad": 17, "precio": 1.20, "costo": 0.80 },
    { "codigo": 610, "descripcion": "PRIMER FACIAL", "cantidad": 0, "precio": 0.85, "costo": 0.50 },
    { "codigo": 611, "descripcion": "PINTURA LABIAL TRADICIONAL", "cantidad": 9, "precio": 0.95, "costo": 0.50 },
    { "codigo": 612, "descripcion": "PINTURA LABIAL MATE", "cantidad": 10, "precio": 1.00, "costo": 0.50 },
    { "codigo": 613, "descripcion": "LAPIZ LABIAL CONTORNO", "cantidad": 6, "precio": 0.90, "costo": 0.30 },
    { "codigo": 614, "descripcion": "LIP GLOS PINTURA TRADICIONAL", "cantidad": 11, "precio": 0.90, "costo": 0.50 },
    { "codigo": 615, "descripcion": "PINTURA NUDE MATE LARGA DURACION", "cantidad": 7, "precio": 1.00, "costo": 0.50 },
    { "codigo": 616, "descripcion": "RUBOR GELATINA", "cantidad": 5, "precio": 1.50, "costo": 0.90 },
    { "codigo": 617, "descripcion": "RUBOR LIQUIDO", "cantidad": 7, "precio": 1.60, "costo": 1.00 },
    { "codigo": 618, "descripcion": "TINTA PARA LABIOS", "cantidad": 57, "precio": 1.00, "costo": 0.65 },
    { "codigo": 619, "descripcion": "COLONIA DUO COLONIA + CREMA", "cantidad": 6, "precio": 2.50, "costo": 1.35 },
    { "codigo": 620, "descripcion": "COLONIA MINI DAMA", "cantidad": 4, "precio": 0.80, "costo": 0.50 },
    { "codigo": 621, "descripcion": "BRILLO DE LABIOS P NINAS FRUTAS", "cantidad": 44, "precio": 0.90, "costo": 0.60 },
    { "codigo": 622, "descripcion": "VASELINA DONA", "cantidad": 2, "precio": 1.00, "costo": 0.85 },
    { "codigo": 623, "descripcion": "VASELINA CARITA FELIZ", "cantidad": 8, "precio": 0.85, "costo": 0.50 },
    { "codigo": 624, "descripcion": "ILUMINADOR CORAZON", "cantidad": 11, "precio": 1.40, "costo": 0.95 },
    { "codigo": 625, "descripcion": "ILUMINADOR EN POLVO", "cantidad": 5, "precio": 1.40, "costo": 1.00 },
    { "codigo": 626, "descripcion": "BRILLO TRANSPARENTE DAMA", "cantidad": 22, "precio": 0.85, "costo": 0.30 },
    { "codigo": 627, "descripcion": "LIP GLOSS 2 EN 1", "cantidad": 8, "precio": 1.00, "costo": 0.50 },
    { "codigo": 628, "descripcion": "VASELINA VASEINA", "cantidad": 6, "precio": 0.85, "costo": 0.35 },
    { "codigo": 629, "descripcion": "BALSAMO FRUTAS MELOCOTON", "cantidad": 15, "precio": 0.95, "costo": 0.70 },
    { "codigo": 630, "descripcion": "PINTURA MAGICA", "cantidad": 16, "precio": 0.80, "costo": 0.30 },
    { "codigo": 631, "descripcion": "PINTURA MA FLOR", "cantidad": 4, "precio": 0.80, "costo": 0.30 },
    { "codigo": 632, "descripcion": "GLITTER EN BARRA", "cantidad": 1, "precio": 1.30, "costo": 0.30 },
    { "codigo": 633, "descripcion": "GLITTER MAQUILLAJE", "cantidad": 6, "precio": 0.80, "costo": 0.30 },
    { "codigo": 634, "descripcion": "PINTURA LABIAL BRILLO", "cantidad": 29, "precio": 1.00, "costo": 0.60 },
    { "codigo": 635, "descripcion": "RIMEL ECONOMICO", "cantidad": 20, "precio": 1.20, "costo": 0.85 },
    { "codigo": 636, "descripcion": "DELINEADOR EYERLINER", "cantidad": 20, "precio": 0.90, "costo": 0.60 },
    { "codigo": 637, "descripcion": "BRILLO FIGURA INFANTIL", "cantidad": 3, "precio": 1.10, "costo": 1.00 },
    { "codigo": 638, "descripcion": "TINTA PARA LABIOS NIÑAS", "cantidad": 6, "precio": 0.90, "costo": 0.60 },
    { "codigo": 639, "descripcion": "DELINEADOR LAPIZ HUDABEUTY", "cantidad": 11, "precio": 1.00, "costo": 0.50 },
    { "codigo": 640, "descripcion": "GLITTER MAQUILLAJE DAMA", "cantidad": 2, "precio": 1.00, "costo": 0.50 },
    { "codigo": 641, "descripcion": "RIMEL 2 EN 1", "cantidad": 1, "precio": 1.50, "costo": 1.00 },
    { "codigo": 642, "descripcion": "LABIAL VARIOS", "cantidad": 5, "precio": 0.70, "costo": 0.50 },
    { "codigo": 643, "descripcion": "LIP GLOSS KUROMI", "cantidad": 19, "precio": 0.90, "costo": 0.45 },
    { "codigo": 644, "descripcion": "ANILLO PARA PEGA *3", "cantidad": 5, "precio": 0.30, "costo": 0.15 },
    { "codigo": 645, "descripcion": "CEPILLO PARA UÑAS", "cantidad": 3, "precio": 0.30, "costo": 0.15 },
    { "codigo": 646, "descripcion": "PINZA PARA UÑAS *3", "cantidad": 1, "precio": 0.50, "costo": 0.30 },
    { "codigo": 647, "descripcion": "RIMEL A PRUEBA DE AGUA", "cantidad": 24, "precio": 1.50, "costo": 0.95 },
    { "codigo": 703, "descripcion": "MINI LAMPARA SEMI", "cantidad": 3, "precio": 2.00, "costo": 1.50 },
    { "codigo": 704, "descripcion": "TINTE PARA CABELLO LOVIA PEQUEÑO", "cantidad": 47, "precio": 1.00, "costo": 0.70 },
    { "codigo": 705, "descripcion": "TINTE PARA CABELLO GRANDE", "cantidad": 32, "precio": 2.50, "costo": 1.73 },
    { "codigo": 706, "descripcion": "AGUA OXIGENADA PARA CABELLO", "cantidad": 7, "precio": 1.20, "costo": 0.70 },
    { "codigo": 707, "descripcion": "SILICON PARA CABELLO", "cantidad": 2, "precio": 5.70, "costo": 3.93 },
    { "codigo": 708, "descripcion": "REPARADOR DE PUNTAS PARA CABELLO", "cantidad": 0, "precio": 1.20, "costo": 1.00 },
    { "codigo": 709, "descripcion": "MASCARILLA KARSELL SOBRE", "cantidad": 25, "precio": 0.90, "costo": 0.40 },
    { "codigo": 710, "descripcion": "MATIZADOR LOVIA", "cantidad": 8, "precio": 0.60, "costo": 0.50 },
    { "codigo": 711, "descripcion": "DECOLORANTE RAPID BLUE", "cantidad": 7, "precio": 2.80, "costo": 1.80 },
    { "codigo": 712, "descripcion": "PEGA LOKA", "cantidad": 20, "precio": 0.40, "costo": 0.20 },
    { "codigo": 713, "descripcion": "NOVEX BLINDAGEM", "cantidad": 4, "precio": 2.00, "costo": 1.50 },
    { "codigo": 714, "descripcion": "PESTANAS MAC 30P", "cantidad": 5, "precio": 1.50, "costo": 1.00 },
    { "codigo": 715, "descripcion": "TINTE PARA CABELLO TUBITO 60ML", "cantidad": 28, "precio": 1.90, "costo": 1.10 },
    { "codigo": 716, "descripcion": "TINTE PARA CABELLO TUBITO 100ML", "cantidad": 5, "precio": 2.50, "costo": 1.60 },
    { "codigo": 717, "descripcion": "DECOLORANTE LOVIA", "cantidad": 3, "precio": 2.00, "costo": 1.50 },
    { "codigo": 718, "descripcion": "LOVIA SHAMPU MATIZANTE POTE 300ML", "cantidad": 1, "precio": 3.50, "costo": 2.50 },
    { "codigo": 719, "descripcion": "PESTANAS MOMBRAY 20P", "cantidad": 27, "precio": 2.10, "costo": 1.45 },
    { "codigo": 720, "descripcion": "BANDOLEROS MOMBRAY", "cantidad": 1, "precio": 6.00, "costo": 4.80 },
    { "codigo": 721, "descripcion": "MONEDERO MOMBRAY", "cantidad": 0, "precio": 4.00, "costo": 2.80 },
    { "codigo": 722, "descripcion": "MATIZANTE LORIANN", "cantidad": 18, "precio": 1.20, "costo": 0.75 },
    { "codigo": 723, "descripcion": "ENVASE SPRAY", "cantidad": 1, "precio": 0.85, "costo": 0.50 },
    { "codigo": 724, "descripcion": "PINCEL VARIOS PARA UÑAS", "cantidad": 6, "precio": 0.50, "costo": 0.30 },
    { "codigo": 725, "descripcion": "PINCEL PARA POLYGEL", "cantidad": 5, "precio": 1.20, "costo": 0.80 },
    { "codigo": 726, "descripcion": "PINCEL LINER CON CRISTALES", "cantidad": 5, "precio": 1.60, "costo": 1.20 },
    { "codigo": 727, "descripcion": "PINZA PARA PESTAÑAS UND", "cantidad": 6, "precio": 1.00, "costo": 0.35 },
    { "codigo": 728, "descripcion": "PINZA PARA PESTANAS 2 UND", "cantidad": 1, "precio": 1.50, "costo": 0.70 },
    { "codigo": 729, "descripcion": "CRISTALES PARA UÑAS GRANDE", "cantidad": 3, "precio": 2.00, "costo": 1.35 },
    { "codigo": 730, "descripcion": "CRISTALES PARA UÑAS PEQ", "cantidad": 1, "precio": 1.70, "costo": 1.10 },
    { "codigo": 731, "descripcion": "SHAROSQUI PARA UÑAS", "cantidad": 2, "precio": 1.00, "costo": 0.60 },
    { "codigo": 732, "descripcion": "PESTAÑAS TIFANY SIRENA", "cantidad": 4, "precio": 1.90, "costo": 1.35 },
    { "codigo": 733, "descripcion": "PESTAÑAS TIFANY AZUL 20P", "cantidad": 6, "precio": 1.95, "costo": 1.35 },
    { "codigo": 734, "descripcion": "PEINE PARA PANCHADO", "cantidad": 20, "precio": 0.70, "costo": 0.30 },
    { "codigo": 735, "descripcion": "PINCEL ACRILICO ECONOMICO", "cantidad": 7, "precio": 0.60, "costo": 0.31 },
    { "codigo": 736, "descripcion": "PINCEL GEL ECONOMICO", "cantidad": 3, "precio": 0.40, "costo": 0.20 },
    { "codigo": 737, "descripcion": "EXFOLIANTE TIFANY", "cantidad": 3, "precio": 2.80, "costo": 1.80 },
    { "codigo": 738, "descripcion": "PEINE TRADICIONAL", "cantidad": 12, "precio": 0.75, "costo": 0.35 },
    { "codigo": 739, "descripcion": "LIMA SPONYI NARANJA", "cantidad": 2, "precio": 0.60, "costo": 0.35 },
    { "codigo": 740, "descripcion": "LIMA 100/180", "cantidad": 23, "precio": 0.45, "costo": 0.25 },
    { "codigo": 741, "descripcion": "TACOS PARA UÑAS", "cantidad": 11, "precio": 0.40, "costo": 0.20 },
    { "codigo": 742, "descripcion": "ALCOHOL PEQUEÑO", "cantidad": 7, "precio": 1.20, "costo": 0.70 },
    { "codigo": 743, "descripcion": "MONOMERO SUPER CRISTAL", "cantidad": 5, "precio": 2.90, "costo": 2.20 },
    { "codigo": 744, "descripcion": "PEGA P/UÑAS MX BON", "cantidad": 10, "precio": 1.00, "costo": 0.60 },
    { "codigo": 745, "descripcion": "ANTI HONGOS M Y", "cantidad": 4, "precio": 1.50, "costo": 0.87 },
    { "codigo": 746, "descripcion": "REMOVEDOR DE ESMALTE MOMBRAY", "cantidad": 1, "precio": 1.40, "costo": 1.00 },
    { "codigo": 747, "descripcion": "REMOVEDOR DE ESMALTE VALMY", "cantidad": 8, "precio": 1.50, "costo": 1.00 },
    { "codigo": 748, "descripcion": "QUIMICA ENDURECEDORA VALMY", "cantidad": 16, "precio": 0.80, "costo": 0.50 },
    { "codigo": 749, "descripcion": "CORTA UÑAS TRIM MEDIANO", "cantidad": 10, "precio": 0.70, "costo": 0.35 },
    { "codigo": 750, "descripcion": "GEL PARA CABELLO DAVEY", "cantidad": 1, "precio": 1.80, "costo": 1.10 },
    { "codigo": 751, "descripcion": "PUNTEROS P/ UNAS UND", "cantidad": 10, "precio": 0.30, "costo": 0.12 },
    { "codigo": 752, "descripcion": "PINCEL LINER", "cantidad": 2, "precio": 0.50, "costo": 0.23 },
    { "codigo": 753, "descripcion": "PINCEL ACRILICO SIRENA", "cantidad": 1, "precio": 0.80, "costo": 0.50 },
    { "codigo": 754, "descripcion": "PESTAÑAS TIFANY 30P", "cantidad": 1, "precio": 2.15, "costo": 1.65 },
    { "codigo": 755, "descripcion": "CAJA REGALO MEDIANA", "cantidad": 8, "precio": 1.30, "costo": 0.75 },
    { "codigo": 756, "descripcion": "SILICON CABELLO AGUACATE", "cantidad": 9, "precio": 3.50, "costo": 2.00 },
    { "codigo": 757, "descripcion": "LAMPARA DE MESA", "cantidad": 1, "precio": 8.50, "costo": 5.50 },
    { "codigo": 758, "descripcion": "BALINES*12", "cantidad": 3, "precio": 2.20, "costo": 1.52 },
    { "codigo": 759, "descripcion": "PESTAÑAS 30P", "cantidad": 11, "precio": 2.40, "costo": 1.80 },
    { "codigo": 760, "descripcion": "ESKALA", "cantidad": 2, "precio": 6.00, "costo": 4.90 },
    { "codigo": 761, "descripcion": "SHAMPU CON ACOND 2 EN 1", "cantidad": 3, "precio": 0.55, "costo": 0.35 },
    { "codigo": 762, "descripcion": "SHAMPU TINTE LOVIA", "cantidad": 2, "precio": 0.85, "costo": 0.40 },
    { "codigo": 763, "descripcion": "TINTE KOLESTINTE", "cantidad": 6, "precio": 2.40, "costo": 1.75 },
    { "codigo": 764, "descripcion": "AMPOLLAS NK", "cantidad": 5, "precio": 2.60, "costo": 1.75 },
    { "codigo": 765, "descripcion": "DESODORANTE TUBITO LADY", "cantidad": 1, "precio": 1.70, "costo": 1.00 },
    { "codigo": 766, "descripcion": "BALINES PLATEADO", "cantidad": 1, "precio": 0.90, "costo": 0.40 },
    { "codigo": 767, "descripcion": "ACEITE KARSELL IMITACION", "cantidad": 5, "precio": 3.00, "costo": 2.00 },
    { "codigo": 768, "descripcion": "GEL PARA CABELLO ECONOMICA", "cantidad": 2, "precio": 0.70, "costo": 0.40 },
    { "codigo": 769, "descripcion": "NUTRIBELLA", "cantidad": 5, "precio": 0.75, "costo": 0.40 },
    { "codigo": 770, "descripcion": "SHAMPU SOBRE", "cantidad": 24, "precio": 0.55, "costo": 0.25 },
    { "codigo": 771, "descripcion": "SHAMPU HUG PEQ", "cantidad": 4, "precio": 1.70, "costo": 1.05 },
    { "codigo": 772, "descripcion": "PESTAÑAS CORRIDA", "cantidad": 1, "precio": 0.50, "costo": 0.30 },
    { "codigo": 773, "descripcion": "PINCEL LINER TIFANNY", "cantidad": 4, "precio": 2.60, "costo": 1.35 },
    { "codigo": 774, "descripcion": "MONOMERO TIFANNY 40", "cantidad": 1, "precio": 2.30, "costo": 1.05 },
    { "codigo": 775, "descripcion": "POLVO ACRILICO DE COLORES", "cantidad": 12, "precio": 1.00, "costo": 0.50 },
    { "codigo": 776, "descripcion": "PESTAÑAS COLORES", "cantidad": 2, "precio": 2.00, "costo": 1.50 },
    { "codigo": 778, "descripcion": "PESTAÑAS MAC 10P", "cantidad": 4, "precio": 1.20, "costo": 0.90 },
    { "codigo": 779, "descripcion": "PINZA PARA CEJAS", "cantidad": 12, "precio": 0.35, "costo": 0.20 },
    { "codigo": 780, "descripcion": "PINCEL POLIGEL", "cantidad": 8, "precio": 1.50, "costo": 0.85 },
    { "codigo": 781, "descripcion": "", "cantidad": 0, "precio": 1.30, "costo": 0.85 },
    { "codigo": 782, "descripcion": "PATA E CABRA UND", "cantidad": 2, "precio": 0.40, "costo": 0.20 },
    { "codigo": 783, "descripcion": "NATURALEZA MUERTA", "cantidad": 3, "precio": 1.20, "costo": 0.85 },
    { "codigo": 784, "descripcion": "MINI CAJITA PARA BISUTERIA", "cantidad": 23, "precio": 0.60, "costo": 0.35 },
    { "codigo": 785, "descripcion": "PINCEL ACRILICO MADERA", "cantidad": 6, "precio": 1.10, "costo": 0.60 },
    { "codigo": 788, "descripcion": "PESTAÑAS 20P MAXGLOW", "cantidad": 13, "precio": 2.00, "costo": 1.35 },
    { "codigo": 789, "descripcion": "ROLDA PEQUEÑÑA", "cantidad": 2, "precio": 2.00, "costo": 1.45 },
    { "codigo": 801, "descripcion": "PULSERA OJITOS", "cantidad": 6, "precio": 2.20, "costo": 1.00 },
    { "codigo": 802, "descripcion": "PULSERA FLOR", "cantidad": 2, "precio": 2.50, "costo": 1.60 },
    { "codigo": 803, "descripcion": "ESCLAVA DAMA", "cantidad": 5, "precio": 2.00, "costo": 1.00 },
    { "codigo": 804, "descripcion": "CADENA ROQUERA", "cantidad": 4, "precio": 2.10, "costo": 0.20 },
    { "codigo": 805, "descripcion": "CADENA DE ACERO CABALLERO 2", "cantidad": 0, "precio": 1.80, "costo": 0 },
    { "codigo": 806, "descripcion": "CADENA DE ACERO CABALLERO 1", "cantidad": 0, "precio": 1.60, "costo": 0 },
    { "codigo": 807, "descripcion": "CADENA ACERO CABALLERO ECONOMICA", "cantidad": 4, "precio": 2.00, "costo": 1.00 },
    { "codigo": 808, "descripcion": "CADENA INFANTIL ACERO", "cantidad": 1, "precio": 2.80, "costo": 1.50 },
    { "codigo": 809, "descripcion": "PINZA METAL", "cantidad": 8, "precio": 1.40, "costo": 0.70 },
    { "codigo": 810, "descripcion": "ARGOLLA MINI ACERO", "cantidad": 1, "precio": 1.00, "costo": 0.50 },
    { "codigo": 811, "descripcion": "ARGOLLA PERLAS", "cantidad": 0, "precio": 1.10, "costo": 0 },
    { "codigo": 812, "descripcion": "ARGOLLA PIEDRA", "cantidad": 7, "precio": 2.10, "costo": 1.10 },
    { "codigo": 813, "descripcion": "ABRIDORES", "cantidad": 13, "precio": 0.50, "costo": 0.20 },
    { "codigo": 814, "descripcion": "TOBILLERAS", "cantidad": 4, "precio": 2.50, "costo": 1.00 },
    { "codigo": 815, "descripcion": "SARCILLOS CON IMAN", "cantidad": 13, "precio": 0.50, "costo": 0.30 },
    { "codigo": 816, "descripcion": "ARGOLLAS LISAS 5", "cantidad": 3, "precio": 0.70, "costo": 0.30 },
    { "codigo": 817, "descripcion": "ARGOLLAS LISAS 3", "cantidad": 2, "precio": 0.60, "costo": 0.30 },
    { "codigo": 818, "descripcion": "ARGOLLAS LISAS 1", "cantidad": 6, "precio": 0.50, "costo": 0.30 },
    { "codigo": 819, "descripcion": "JUEGO DE ACERO", "cantidad": 13, "precio": 1.40, "costo": 0.80 },
    { "codigo": 820, "descripcion": "PEIRCING NARIZ", "cantidad": 16, "precio": 0.20, "costo": 0.10 },
    { "codigo": 821, "descripcion": "ANILLOS NIÑA", "cantidad": 4, "precio": 1.00, "costo": 0.80 },
    { "codigo": 822, "descripcion": "SARCILLOS HOMBRES", "cantidad": 33, "precio": 0.30, "costo": 0.10 },
    { "codigo": 823, "descripcion": "TUNEL CABALLERO", "cantidad": 6, "precio": 0.50, "costo": 0.30 },
    { "codigo": 824, "descripcion": "CINTILLOS GAMUZA", "cantidad": 0, "precio": 1.00, "costo": 0.70 },
    { "codigo": 825, "descripcion": "CINTILLOS GAMUZA ESCARCHA", "cantidad": 1, "precio": 1.40, "costo": 1.00 },
    { "codigo": 826, "descripcion": "CINTILLO NEGRO PIEDRA", "cantidad": 0, "precio": 1.40, "costo": 1.00 },
    { "codigo": 827, "descripcion": "MORRAL + BANDOLERO+MONEDERO", "cantidad": 3, "precio": 14.50, "costo": 10.50 },
    { "codigo": 828, "descripcion": "UÑAS CLASICAS BOLSITAS", "cantidad": 54, "precio": 0.25, "costo": 0.20 },
    { "codigo": 829, "descripcion": "MIN GANCHO PLASTICO PERLA PAR", "cantidad": 1, "precio": 0.80, "costo": 0.40 },
    { "codigo": 830, "descripcion": "GANCHO PLASTICO PERLA", "cantidad": 4, "precio": 0.80, "costo": 0.40 },
    { "codigo": 831, "descripcion": "CARRITO INFANTIL CUTE", "cantidad": 0, "precio": 2.10, "costo": 1.00 },
    { "codigo": 832, "descripcion": "JUGUETE NIÑA VARIADO", "cantidad": 0, "precio": 1.15, "costo": 0.50 },
    { "codigo": 833, "descripcion": "COLLAR DE LUJO", "cantidad": 6, "precio": 2.50, "costo": 1.50 },
    { "codigo": 834, "descripcion": "SARCILLO ECONOMICO", "cantidad": 55, "precio": 0.20, "costo": 0.10 },
    { "codigo": 835, "descripcion": "PIERCING", "cantidad": 37, "precio": 0.30, "costo": 0.15 },
    { "codigo": 836, "descripcion": "JUEGO DE ACERO INFANTIL", "cantidad": 1, "precio": 1.20, "costo": 0.85 },
    { "codigo": 837, "descripcion": "JUEGO FANTASIA NIÑA", "cantidad": 1, "precio": 1.00, "costo": 0.50 },
    { "codigo": 838, "descripcion": "CADENA DOBLE FLORES", "cantidad": 1, "precio": 3.00, "costo": 1.65 },
    { "codigo": 839, "descripcion": "TUNEL METAL", "cantidad": 17, "precio": 0.60, "costo": 0.30 },
    { "codigo": 840, "descripcion": "CADENA TREBOL", "cantidad": 5, "precio": 2.40, "costo": 1.70 },
    { "codigo": 841, "descripcion": "PINCITA PAR ACERO", "cantidad": 4, "precio": 1.40, "costo": 0.70 },
    { "codigo": 842, "descripcion": "CINTILLO METAL PIEDRA", "cantidad": 1, "precio": 1.40, "costo": 0.90 },
    { "codigo": 843, "descripcion": "JUEGO ACERO YUROMI", "cantidad": 2, "precio": 1.50, "costo": 1.00 },
    { "codigo": 844, "descripcion": "PIERCING OMBLIGO DORADO", "cantidad": 10, "precio": 1.40, "costo": 0.85 },
    { "codigo": 845, "descripcion": "PIERCING *3 NEGRO", "cantidad": 11, "precio": 0.60, "costo": 0.30 },
    { "codigo": 846, "descripcion": "ROSARIO", "cantidad": 2, "precio": 3.50, "costo": 2.50 },
    { "codigo": 847, "descripcion": "SARCILLOS", "cantidad": 25, "precio": 0.40, "costo": 0.20 },
    { "codigo": 848, "descripcion": "ANILLO DAMA", "cantidad": 6, "precio": 2.00, "costo": 1.30 },
    { "codigo": 875, "descripcion": "PINZA BANANA", "cantidad": 2, "precio": 1.20, "costo": 0.70 },
    { "codigo": 876, "descripcion": "ARGOLLA OJITO", "cantidad": 2, "precio": 1.60, "costo": 1.00 },
    { "codigo": 877, "descripcion": "COLLAR PERLA", "cantidad": 2, "precio": 2.00, "costo": 1.10 },
    { "codigo": 878, "descripcion": "TOBILLERAS ORO", "cantidad": 4, "precio": 2.50, "costo": 0.85 },
    { "codigo": 879, "descripcion": "CADENA OJITO", "cantidad": 0, "precio": 1.05, "costo": 0 },
    { "codigo": 880, "descripcion": "ESCLAVA CABALLERO", "cantidad": 2, "precio": 3.00, "costo": 1.25 },
    { "codigo": 881, "descripcion": "TOPITO PERLA", "cantidad": 10, "precio": 0.90, "costo": 0.35 },
    { "codigo": 882, "descripcion": "TOPITOS DORADOS", "cantidad": 1, "precio": 0.50, "costo": 0.20 },
    { "codigo": 883, "descripcion": "ARGOLLAS SENCILLAS", "cantidad": 4, "precio": 1.50, "costo": 0.80 },
    { "codigo": 884, "descripcion": "SARCILLOS PERLA FANTASIA", "cantidad": 6, "precio": 0.90, "costo": 0.30 },
    { "codigo": 885, "descripcion": "MINI GANCHO MARRON", "cantidad": 6, "precio": 0.70, "costo": 0.30 },
    { "codigo": 886, "descripcion": "ARGOLLA FIGURA", "cantidad": 3, "precio": 1.10, "costo": 0.70 },
    { "codigo": 901, "descripcion": "UÑAS PARA ACRILICAS", "cantidad": 2, "precio": 2.00, "costo": 0.85 },
    { "codigo": 902, "descripcion": "CEPILLO REDONDO MADERA", "cantidad": 6, "precio": 1.50, "costo": 0.85 },
    { "codigo": 903, "descripcion": "UÑAS 5D", "cantidad": 1, "precio": 2.40, "costo": 1.70 },
    { "codigo": 904, "descripcion": "BOLSA REGALO GRANDE PAPEL", "cantidad": 4, "precio": 0.85, "costo": 0.50 },
    { "codigo": 905, "descripcion": "BOLSA REGALO MEDIANA METALIZADA", "cantidad": 1, "precio": 0.65, "costo": 0.35 },
    { "codigo": 906, "descripcion": "LIGAS MINI", "cantidad": 24, "precio": 0.30, "costo": 0.16 },
    { "codigo": 907, "descripcion": "BORLA MAQUILLAJE UNID", "cantidad": 2, "precio": 0.40, "costo": 0.20 },
    { "codigo": 908, "descripcion": "COLITAS PEPAS", "cantidad": 1, "precio": 0.35, "costo": 0.15 },
    { "codigo": 909, "descripcion": "TIJERA PARA CEJAS ECONOMICA", "cantidad": 3, "precio": 1.20, "costo": 0.80 },
    { "codigo": 910, "descripcion": "UÑAS ALMENDRA 100UND MY", "cantidad": 0, "precio": 1.50, "costo": 1.00 },
    { "codigo": 911, "descripcion": "TIJERA PARA CEJAS CON PEINE", "cantidad": 2, "precio": 1.00, "costo": 0.50 },
    { "codigo": 912, "descripcion": "UÑAS CON PIEDRA", "cantidad": 0, "precio": 1.30, "costo": 0.85 },
    { "codigo": 913, "descripcion": "UÑAS FASHION 24 UND", "cantidad": 1, "precio": 2.00, "costo": 1.30 },
    { "codigo": 914, "descripcion": "PINCEL ACRILICO *3", "cantidad": 3, "precio": 2.10, "costo": 1.10 },
    { "codigo": 915, "descripcion": "UÑAS ALMENDRA MAXGLOW 300UND", "cantidad": 2, "precio": 4.20, "costo": 3.20 },
    { "codigo": 916, "descripcion": "PINZAS DE NIÑAS LAZO", "cantidad": 4, "precio": 1.50, "costo": 0.95 },
    { "codigo": 917, "descripcion": "PALETA CONTORNO", "cantidad": 5, "precio": 1.80, "costo": 1.10 },
    { "codigo": 918, "descripcion": "CANECALON UNICOLOR", "cantidad": 7, "precio": 2.90, "costo": 1.80 },
    { "codigo": 919, "descripcion": "CANECALON BICOLOR", "cantidad": 6, "precio": 2.70, "costo": 1.60 },
    { "codigo": 920, "descripcion": "CINTILLO MICKY", "cantidad": 6, "precio": 1.00, "costo": 0.50 },
    { "codigo": 921, "descripcion": "EXTENSION MECHAS", "cantidad": 6, "precio": 0.90, "costo": 0.50 },
    { "codigo": 922, "descripcion": "BOLSO TERMICO", "cantidad": 1, "precio": 5.00, "costo": 3.50 }

   ]